name: Deploy Functions to Supabase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: |
          supabase functions deploy comuni --no-verify-jwt --project-ref $PROJECT_ID
          supabase functions deploy province --no-verify-jwt --project-ref $PROJECT_ID
          supabase functions deploy regioni --no-verify-jwt --project-ref $PROJECT_ID